//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BankTransactions = new HashSet<BankTransaction>();
        }
    
        public int Id { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string AccountNumber { get; set; }
        public long Balance { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string AccountTitle { get; set; }
        public string OtherDetail { get; set; }
    
        public virtual ICollection<BankTransaction> BankTransactions { get; set; }
    }
}
