//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public int Id { get; set; }
        public string DealerName { get; set; }
        public string CNIC { get; set; }
        public string EmailId { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public int PartyId { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
