//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAMS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZamsEntities6 : DbContext
    {
        public ZamsEntities6()
            : base("name=ZamsEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank> Banks { get; set; }
        public DbSet<BankTransaction> BankTransactions { get; set; }
        public DbSet<ContractParty> ContractParties { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Party> Parties { get; set; }
        public DbSet<PettyCash> PettyCashes { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<ReverseEntry> ReverseEntries { get; set; }
    }
}
