//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.ContractParties = new HashSet<ContractParty>();
            this.Transactions = new HashSet<Transaction>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public string Party_Name { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string OwnerName { get; set; }
        public string Email { get; set; }
        public Nullable<long> CompanyBalance { get; set; }
        public string CompanyType { get; set; }
        public string CNIC_NTN { get; set; }
    
        public virtual ICollection<ContractParty> ContractParties { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
