//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ContractParties = new HashSet<ContractParty>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public int OwnerPartyId { get; set; }
        public Nullable<System.DateTime> EstimatedStartDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> EstimatedEndDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public long InitialBalance { get; set; }
        public long CurrentBalance { get; set; }
        public long Credit { get; set; }
    
        public virtual ICollection<ContractParty> ContractParties { get; set; }
        public virtual Party Party { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
