//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReverseEntry
    {
        public long Id { get; set; }
        public long ReverseID { get; set; }
        public string TableName { get; set; }
        public long Amount { get; set; }
        public Nullable<System.DateTime> trDate { get; set; }
        public Nullable<int> TransactionID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
